### PR TITLE
Cookie modal set tracking cookies correctly HP-2500

### PR DESCRIPTION
**Pull request by mikkojamG**
CookieModal and CookiePage are not currently setting tracking cookies correctly. TrackEvent and TrackPageView should check for consent.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr381-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr381-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr381-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr381-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Review by Riippi — APPROVED** [review]
👍

**Pull request merged**
