### PR TITLE
Replace old matomo tracking HP-2500

### PR DESCRIPTION
**Pull request by mikkojamG**
Replace old Matomo tracking.

Azure: https://dev.azure.com/City-of-Helsinki/helsinki-profile-ui/_git/helsinki-profile-ui-aok/pullrequest/9081

### CODE REVIEW

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr375-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr375-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr375-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by Riippi** [comment]
I can't start this locally. I get only a white page. Does this need the azure pr merged?

**Comment by mikkojamG** [comment]
> I can't start this locally. I get only a white page. Does this need the azure pr merged

Added placeholder values so that MatomoTracker does not throw error.

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr375-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Review by Riippi — APPROVED** [review]
👍

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr375-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr375-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
