### PR TITLE
feat: bump Node version to 18.18.2 HP-1841

### PR DESCRIPTION
**Pull request by mikkojamG**
## Description
Upgrading Node.js version to 18.18.2 and updating Dockerfile accordingly. Some dependency updates included.

## Related Issue(s)

**[HP-1841](https://helsinkisolutionoffice.atlassian.net/browse/HP-1841)**

## How Has This Been Tested?

Manually, and the CI pipeline passes.

[HP-1841]: https://helsinkisolutionoffice.atlassian.net/browse/HP-1841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr308-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr308-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr308-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr308-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Review by Riippi — APPROVED** [review]

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr308-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
