### PR TITLE
HP-834: Upgrade react-scripts

### PR DESCRIPTION
**Pull request by NikoHelle**

### CODE REVIEW

**Review by akikoskinen — COMMENTED** [review]
This update seems to bring in a new version of pretty much every babel plugin and some other packages, _in addition_ to the already existing version. For example there are now no less than three different versions of `@babel/preset-env` in the `yarn.lock` file (there were already two before this PR). Is there a way to avoid this massive increase in different package versions?

**Comment by NikoHelle** [comment]
React-scripts is a dependency monster. But this is probably a yarn issue - same with lodash-versions in another PR. 
Have to run clean yarn install for this one too, after https://github.com/City-of-Helsinki/open-city-profile-ui/pull/179

**Comment by NikoHelle** [comment]
After clean install, this PR looks better too.

**Review by akikoskinen — APPROVED** [review]
Yes, much cleaner now.

**Pull request merged**
