### PR TITLE
Replace Apollo client codegen with graphql-codegen HP-2080

### PR DESCRIPTION
**Pull request by mikkojamG**
Replacing deprecated Apollo client codegen with `graphql-codegen`. Upgrading `apollo/client` to latest version and removing redundant dependencies such as `apollo`.

https://helsinkisolutionoffice.atlassian.net/browse/HP-2080

### CODE REVIEW

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr322-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr322-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr322-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr322-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Review by Riippi — APPROVED** [review]
LGTM

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr322-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr322-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr322-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
